import { Space_Grotesk, Fira_Code } from "next/font/google"

import type { Metadata } from "next"

// eslint-disable-next-line no-restricted-imports
import "./globals.css"

const primaryFont = Space_Grotesk({
  variable: "--font-primary",
  subsets: ["latin"],
})

const secondaryFont = Fira_Code({
  variable: "--font-secondary",
  subsets: ["latin"],
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body
        className={`${primaryFont.variable} ${secondaryFont.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  )
}
